version: 1.0.{build}.{branch}

build: off

matrix:
  fast_finish: true

platform:
  - x64

test_script:
  - choco install pypy3
  - pypy3 --version
  - pypy3 check.py
  - py -3.7 check.py
  - py -3.7 -m pip install --upgrade pip
  - py -3.7 -m pip install --upgrade virtualenv
  - py -3.7 -m virtualenv venv -p pypy3
