version: 1.0.{build}.{branch}

build: off

matrix:
  fast_finish: true

# Use 32-bit platform to match the word size of PyPy `.zip`
platform:
  - x86

test_script:
  - install.bat
  - pypy3 --version
  - pypy3 check.py
