version: 1.0.{build}.{branch}

build: off

matrix:
  fast_finish: true

# Always use a 64-bit machine.
platform:
  - x64

install:
  - choco install pypy3 -fdv -s "'.;https://chocolatey.org/api/v2/'"

test_script:
  - pypy3 --version
  - pypy3 check.py
